# Generated by Django 4.2.2 on 2023-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0007_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=150)),
                ('contraseña', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
