# Generated by Django 4.2.2 on 2023-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0009_delete_nuevousuario_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña_user',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.IntegerField(default='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_user',
            field=models.CharField(default='usuario', max_length=50),
        ),
    ]
