# Generated by Django 4.2.2 on 2023-06-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0010_alter_usuario_contraseña_user_alter_usuario_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña_user',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_user',
            new_name='idusuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_user',
            new_name='nombre',
        ),
    ]
