# Generated by Django 4.2.6 on 2023-10-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0013_alter_userprofile_altura_alter_userprofile_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(null=True, upload_to='imagenesProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
